### PR TITLE
Updates to validating with Rego and CEL

### LINKED ISSUE #8: Implement Terraform resource validation using Rego Policies
Implement validation mechanism for different Terraform resources using Rego policies.

### LINKED ISSUE #10: Add a command to show JSON representation of generated Dockerfile
Introduce a command/flag to display the `JSON` representation of the generated Dockerfile and input Terraform resources when using the `--mode container` or `--mode tf`  option.

The displayed `JSON` structure would help users to write custom policies/rules for validating generated Dockerfiles, and Terraform resources based on the JSON structure.

### LINKED ISSUE #11: Add suport for validation using CEL - Common Expression Language
Add suport for validation using [CEL](https://github.com/google/cel-spec/blob/master/doc/langdef.md)

### PR DESCRIPTION
**Pull request by santoshkal**
This PR adds more validation features to Genval. 
- Validation of Kubernetes resource manifests with Rego policies
- Validation of Terraform `.tf` resource files  with rego policies -  closes #8 
- Validation of Kubernetes resource manifests with CEL policies. -  Closes #11 
- Adds helper mode `--showjson` to show JSON representation of the input, this would help users write custom Rego/CEL policies. Closes #10 
- Now Genval can validate/generate multiple Kubernetes/CRDs config files in `cue` mode. The generated manifests will be stored in `./output` directory. - Coses #9

@MrAzharuddin

### CODE REVIEW

**Comment by chandu-intelops** [comment]
@santoshkal , resolve the conflicts please

**Review by MrAzharuddin — COMMENTED** [review]
@santoshkal , Please move the build file to root and make it executable anywhere. 
Instead of ./genval , This should be genval [Command]

**Review by MrAzharuddin — APPROVED** [review]
@santoshkal ,

Please look at the comment and add autocompletion as well and fix in the next PR.
Approving this PR with the above mentioned changed required.


@chandu-intelops @devopstoday11 FYI

**Comment by santoshkal** [comment]
> @santoshkal , resolve the conflicts please

>  got some conflicts, Please resolve and getback with the above mentioned changed required.

@MrAzharuddin @devopstoday11 
Resolved the conflicts and is now ready to be merged.

**Comment by santoshkal** [comment]
> @santoshkal , Please move the build file to root and make it executable anywhere. Instead of ./genval , This should be genval [Command]

Update the Makefile path for `genval` executable to `cwd` instead of `./bin/genval` currently.
Thanks!

**Review by chandu-intelops — APPROVED** [review]

**Pull request merged**
